<?php $_config_vars = array (
  'welcome' => 'Selamat Datang',
  'rememberme' => 'Ingat saya',
  'home' => 'Home',
  'login' => 'Login',
  'LOGIN' => 'LOGIN',
  'logout' => 'Logout',
  'en' => 'en',
  'ina' => 'ina',
  'nl' => 'nl',
  'username' => 'Username',
  'password' => 'Password',
  'wrongpassword' => 'Password tidak benar.<br/>Klik <a href=\'getpassword.php\' title=\'kirim password\'>disini</a> apabila anda lupa dengan password anda.',
  'name' => 'Nama',
  'email' => 'Email',
  'passwordagain' => 'Ulangi password anda',
  'reset' => 'Hapus',
  'newuser' => 'User baru',
  'registernewuser' => 'Username tidak ditemukan di database, silakan register terlebih dahulu.',
  'activationcode' => 'Kode aktivasi',
  'nonews' => 'Berita tidak ditemukan.',
  'getactivation' => 'Kirim kode aktivasi',
  'location' => 'Lokasi',
  'interest' => 'Interest',
  'publicemail' => 'Email publik',
  'joindate' => 'Tanggal bergabung',
  'edit' => 'ganti',
  'cancel' => 'batal',
  'deletecomment' => 'Hapus komentar',
  'date' => 'TANGGAL',
  'nosavednews' => 'Tidak ada berita yang disimpan.',
  'nopostnews' => 'Tidak ada berita yang disubmit.',
  'nocomments' => 'Tidak ada komentar.',
  'newslink' => 'Link berita',
  'newstitle' => 'Judul',
  'newsdescription' => 'Penjelasan singkat',
  'newskeywords' => 'Kata kunci',
  'newsusescreenshots' => 'Gunakan screenshot',
  'newsscreenshots' => 'Link screenshot',
  'newstopic' => 'Pilih topic berita',
  'newstype' => 'Pilih tipe berita',
  'pleasechoose' => 'Silakan pilih',
  'submitnewsnow' => 'Submit berita anda di Kafeinfo dan tunjukkan kepada dunia sekarang juga. <a href=\'about.php\' target=\'_blank\'>LEBIH LANJUT.</a>',
  'editnewsnow' => 'Anda sedang mengedit berita anda, <a href=\'news.php\'>batal</a>.',
  'duplicatefound' => 'Duplikat berita ditemukan di database kami.',
  'tryagain' => 'Silakan <a href=\\\'submit.php\\\'>coba</a> sekali lagi.',
  'newssubmitted' => 'Berita telah sukses disubmit.',
  'newsupdated' => 'Berita telah sukses diupdate.',
  'redirecttodashboard' => 'Anda akan segera di-redirect ke dashboard anda.',
  'somethingiswrong' => 'Kami mohon maaf, ada suatu kesalahan.',
  'displayingsearch' => 'Hasil pencarian untuk : ',
  'tools' => 'TOOLS',
  'topnews' => 'BERITA UNGGULAN',
  'newsnotfound' => 'Berita tidak ditemukan',
  'newnews' => 'BERITA BARU',
  'removescreenshot' => 'Apakah anda yakin anda tidak ingin menggunakan screenshot?',
  'welcome1' => 'Selamat datang di Kafeinfo Bookmarking Sosial, silakan melihat halaman <a href=\'upcoming.php\' title=\'BERITA BARU\'>BERITA BARU</a> untuk membaca berita terkini.',
  'fillallfield' => 'Kolom username dan password harap diisi.',
  'fillfield' => 'Semua kolom harap diisi.',
  'fieldempty' => 'Harap diisi.',
  'emailnotvalid' => 'Email yang anda masukkan tidak valid, harap cek kembali.',
  'activatenow' => 'Registrasi anda telah kami terima, silakan cek email<br/> anda, dan masukkan kode aktivasi anda dibawah ini',
  'aboutkafeinfo' => 'Tentang Kafeinfo',
  'terms' => 'KETENTUAN PAKAI',
  'termsofuse' => 'Ketentuan pakai',
  'developersblog' => 'Blog developer',
  'register' => 'Register',
  'about' => 'TENTANG KAFEINFO',
  'howto' => 'CARA KERJA',
  'creator' => 'TIM KAFEINFO',
  'allmedia' => 'SEMUA MEDIA',
  'news' => 'BERITA',
  'image' => 'GAMBAR',
  'video' => 'VIDEO',
  'popular' => 'POPULER',
  'upcoming' => 'BERITA BARU',
  'technology' => 'TEKNOLOGI',
  'sports' => 'OLAH RAGA',
  'health' => 'KESEHATAN',
  'world' => 'DUNIA',
  'business' => 'BISNIS',
  'comedy' => 'KOMEDI',
  'socialpolitic' => 'SOSPOL',
  'musicfilm' => 'MUSIK FILM',
  'other' => 'LAIN LAIN',
  'submitnews' => 'KIRIM BERITA',
  'yourdashboard' => 'DASHBOARD ANDA',
  'yourprofile' => 'PROFIL ANDA',
  'yourregister' => 'REGISTRASI',
  'forgotpassword' => 'LUPA PASSWORD?',
  'createaccount' => '1. REGISTRASI',
  'sendnews' => '2. KIRIM BERITA',
  'votenews' => '3. PILIH BERITA',
  'profile' => 'PROFIL',
  'favorites' => 'DISIMPAN',
  'comments' => 'KOMENTAR',
  'voteup' => 'PILIH BERITA',
  'votedown' => 'KUBUR BERITA',
  'vote' => 'PILIHAN',
  'postedby' => 'Berita oleh',
  'at' => 'pada',
  'viewdetails' => 'LIHAT DETAIL BERITA',
  'voted' => 'TERPILIH',
  'buried' => 'TERKUBUR',
  'viewcomment' => 'Lihat komentar',
  'addcomments' => 'Beri komentar',
  'commentsmall' => 'Komentar',
  'by' => 'Oleh',
  'reportnewstext' => 'LAPORKAN BERITA INI APABILA TIDAK SESUAI DENGAN KETENTUAN PAKAI',
  'reported' => 'TELAH DILAPORKAN',
  'viewnews' => 'Lihat berita',
  'deletefavorite' => 'Hapus berita',
  'kafeinfobookmarkingsosial' => 'Kafeinfo Bookmarking Sosial',
  'description1' => 'Kafeinfo adalah pengembangan dari konsep social bookmarking yang tengah popular di komunitas online internasional. Kafeinfo merupakan tempat dimana anda dapat turut serta dalam menyampaikan berita-berita menarik terkini kepada dunia. Hanya dengan memasukkan link berita yang anda anggap layak dan menarik untuk ditampilkan, anda telah menjadi kontributor Kafeinfo.',
  'description2' => 'Tidak hanya itu, orang lain yang menganggap berita anda menarik dapat mempopulerkan berita tersebut dengan system voting. Semakin banyak vote yang anda raih, semakin tinggi rating berita anda. Di masa serba cepat seperti sekarang ini, anda dapat menghemat banyak waktu dalam mencari berita-berita terkini hanya dengan mengunjungi satu situs. Dengan alasan itulah Kafeinfo hadir untuk menjadi alternatif utama bagi anda yang haus berita.',
  'description3' => 'Berbagai macam klasifikasi berita mulai dari berita politik sampai hiburan tersedia untuk memudahkan anda mencari berita yang anda inginkan. Tidak hanya lokal, berita internasional pun dapat anda masukkan dan akses di Kafeinfo. Berbeda dengan situs berita lain, Kafeinfo menyediakan sarana dialog bagi para pembaca berita untuk berdiskusi. Kafeinfo sebagi komunitas kolektif memudahkan anda bertukar pikiran bersama anggota lain melalui komentar dan opini mengenai berita tertentu.',
  'votebury' => 'Vote and Bury news',
  'vote1' => 'Dengan sistim voting dan kubur Kafeinfo, anda dapat membantu menentukan berita mana yang layak untuk ditampilkan di halaman utama Kafeinfo Bookmarking Sosial dan mana yang sudak basi atau tidak layak lagi untuk ditampilkan di halaman utama Kafeinfo Bookmarking Sosial.',
  'vote2' => 'Setiap berita yang anda submit akan mendapatkan nilai voting 1 dan akan berada di halaman Berita Baru. Apabila orang lain membacanya menganggap berita itu menarik dan layak untuk ditampilkan di halaman depan, mereka dapat mem-voting berita anda sehingga nilai voting akan naik menjadi 2. Setelah berita ini mendapat nilai voting 5, berita ini secara otomatis akan ditampilkan di halaman populer Kafeinfo Bookmarking Sosial.',
  'dashboard' => 'Dashboard',
  'dashboard1' => 'Dashboard Kafeinfo adalah sebuah tempat dimana anda dapat melihat kembali berita, komentar yang pernah anda posting. Hal ini memudahkan anda untuk mengupdate sebuah berita atau menghapus berita tersebut apabila berita tersebut sudah basi atau link sudah tidak bekerja lagi.',
  'dashboard2' => 'Anda juga dapat memfavoritkan berita-berita yang anda anggap menarik di Kafeinfo Bookmarking Sosial untuk mengaksesnya lebih cepat di dashboard anda.',
  'comment' => 'Komentar anda yang paling ditunggu.',
  'comment1' => 'Untuk menyediakan sarana dialog antara pengguna Kafeinfo Bookmarking Sosial, kami menyediakan sistem komentar pada setiap berita-berita yang disubmit di Kafeinfo Bookmarking Sosial.',
  'creatorfarrah' => 'Farrah adalah Sarjana Manajemen Komunikasi Hogeschool INHolland dan Management Trainee Marketing di British American Tobacco, Belanda. Farrah bertanggung jawab dalam mengembangkan konsep kreatif dan promosi Kafeinfo.',
  'creatorakbar' => 'Kafeinfo adalah salah satu project yang didirikan berdasarkan ketertarikannya kita pada Web 2.0 dan sebagai wadah berbagi berita berita menarik dan aktual diseluruh dunia.',
  'creatordimas' => 'Dimas adalah Sarjana Manajemen Komunikasi Hogeschool INHolland dan Community Manager di SellaBand Belanda. Bersama dengan Farrah, Dimas bertanggung jawab dalam mengembangkan konsep kreatif dan promosi Kafeinfo.',
  'usernamecharacter' => 'Username anda mengandung karakter invalid.',
  'emailinvalid' => 'Alamat email yang anda masukkan tidak valid.',
  'usernameexist' => 'Username yang anda pilih tidak tersedia.',
  'emailexist' => 'Email telah ditemukan dalam database kami.',
  'passwordlength' => 'Password minimal 5 karakter.',
  'usernamenotfound' => 'Username tidak ditemukan.<br/>Silakan register terlebih dahulu <a href=\'register.php\' title=\'register\'>disini</a>.',
  'usernotfound' => 'User tidak ditemukan <br/>Silakan register terlebih dahulu <a href=\'register.php\' title=\'register\'>disini</a>.',
  'usernamedifferent' => 'Username yang anda masukkan tidak benar. <br/>Silakan coba sekali lagi.',
  'getactivationsuccess' => 'Kode aktivasi anda telah terkirim. <br/>Cek spam box anda apabila anda tidak menemukan di inbox.',
  'passworddifferent' => 'Kedua password yang anda masukkan tidak sama.',
  'login_box_text' => 'Login segera dengan username dan password anda. <br/> Klik <a href=\'getpassword.php\' title=\'kirim password\'>disini</a> apabila anda lupa dengan password anda.',
  'register_box_text' => 'Segera bergabung dalam komunitas<br/>Kafeinfo Bookmarking Sosial',
  'registertermsofuse' => 'Dengan menekan tombol submit, anda telah setuju terhadap <a href=\'termsofuse.php\' style="text-decoration:underline;"title=\'Ketentuan pakai\' target=\'_blank\'>Ketentuan pakai</a><br/>Kafeinfo Bookmarking Sosial yang telah ditentukan.',
  'activatefirst' => 'Masukkan kode aktivasi yang terdapat di email registrasi anda.<br/>Klik <a href=\'getactivation.php\' title=\'Kirim kode aktivasi\'>disini</a> untuk mengirimkan kode aktivasi kembali.',
  'norecordemail' => 'Email tidak dapat ditemukan di sistim kami.<br/>Silakan register terlebih dahulu <a href=\'register.php\' title=\'Registrasi\'>disini</a>.',
  'wrongactivationcode' => 'Kode aktivasi tidak benar.<br/>Silakan cek kode aktivasi anda dan coba lagi.',
  'pleasetryagain' => 'Maaf ada yang salah dengan sistem kami<br/>Silakan coba kembali.',
  'accountactivated' => 'Akun anda telah diaktifkan <br/>Silakan login dengan username dan password anda.',
  'pleaseloginvotingup' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> untuk memilih berita.',
  'pleaseloginvotingdown' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> untuk mengubur berita.',
  'pleaselogincomment' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> sekarang juga untuk mengirimkan komentar.',
  'pleaseloginviewprofile' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> untuk melihat profil.',
  'pleaseloginfavorite' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> untuk menyimpan berita ini.',
  'pleaseloginreport' => 'Silakan <a href=login>Login</a> atau <a href=register>Register</a> sekarang juga untuk melaporkan berita ini.',
  'getactivationtext' => 'Masukkan email dan username anda untuk<br/>mengirimkan kode aktivasi kembali.',
  'nocommentsyet' => 'Belum ada komentar, anda bisa menjadi yang pertama!',
  'send' => 'Kirim',
  'addcomment' => 'Kirim komentar',
  'nohtml' => 'HTML tidak diperbolehkan.',
  'reloadcomment' => 'Refresh komentar',
  'reportnews' => 'LAPORKAN BERITA INI',
  'favoritenews' => 'SIMPAN BERITA INI',
  'pleasefillcomment' => 'Kolom komentar harap diisi terlebih dahulu.',
  'saved' => 'TERSIMPAN',
  'deletecommentconfirmation' => 'Apakah anda yakin mau menghapus komentar ini?',
  'deletefavouriteconfirmation' => 'Apakah anda yakin mau menghapus berita yang anda simpan?',
  'deletenewsconfirmation' => 'Apakah anda yakin mau menghapus berita ini?',
  'activationinfo' => 'Apabila anda tidak menemukan email aktivasi dari Kafeinfo<br/> Silakan cek spam box anda, atau <a style="text-decoration:underline;" href=\'getactivation.php\'>kirim email aktivasi kembali</a>.',
  'getpasswordtext' => 'Masukkan email dan username anda untuk mengirimkan <br/> password baru anda.',
  'usernamenotmatch' => 'Username tidak cocok dengan email yang anda<br/> masukkan, Silakan coba kembali.',
  'passwordsent' => 'Password baru anda telah terkirim, <br/>Silakan cek email anda.',
  'usernameinfo' => 'harap memakai huruf dan angka saja',
  'passwordinfo' => 'password minimal 5 karakter',
); ?>